services:
  apache:
    image: httpd:latest
    container_name: apache_server
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/local/apache2/htdocs/
    networks:
      - webnet
networks:
  webnet:
    driver: bridge